version: '3'
services:
  balancer:
    image: nginx
    volumes:
    # cleaner way would be to add new file and mix with default, but it always leads to endless pain and suffering
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
     - ./static/:/usr/share/nginx/html/static/
    ports:
     - "8888:80"
#    environment:
#     - NGINX_HOST=foobar.com
#     - NGINX_PORT=80
#    command: [nginx-debug, '-g', 'daemon off;']
  akka-service:
    image: dragsasgard/dataroot_hello_akka
#    volumes:
#     - ./mysite.template:/etc/nginx/conf.d/mysite.template
#  akka:
#    image: dragsasgard/dataroot_hello_akka
#    ports:
#      - "7777:8080"
