version: '3'
services:
  balancer:
    image: nginx
    volumes:
    # cleaner way would be to add new file and mix with default, but it always leads to unbearable pain and endless suffering
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
     - ./static/:/usr/share/nginx/html/static/
    ports:
     - "8888:80"
  akka-service:
    image: dragsasgard/dataroot_hello_akka
